# Generated by Django 5.2.3 on 2025-06-27 11:28

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UoM',
            fields=[
                ('uom_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('conversion_to_si', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('costing_method', models.CharField(choices=[('FIFO', 'FIFO'), ('AVG', 'Average'), ('STD', 'Standard')], default='AVG', max_length=10)),
                ('tracking_method', models.CharField(choices=[('NONE', 'None'), ('SERIAL', 'Serial'), ('BATCH', 'Batch')], default='NONE', max_length=10)),
                ('safety_stock', models.PositiveIntegerField(default=0)),
                ('reorder_qty', models.PositiveIntegerField(default=0)),
                ('cogs_account_id', models.IntegerField(blank=True, null=True)),
                ('inventory_account_id', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.organization')),
                ('base_uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='base_products', to='product.uom')),
            ],
            options={
                'unique_together': {('organization', 'product_code')},
            },
        ),
        migrations.CreateModel(
            name='ProductUoM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.FloatField(help_text='Multiply by this to convert to base unit')),
                ('is_default_sales', models.BooleanField(default=False)),
                ('is_default_purchase', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.uom')),
            ],
            options={
                'unique_together': {('product', 'uom')},
            },
        ),
    ]
